### ISSUE TITLE
Add Vault Name Validation 

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/wallet#1208]
- regex validation
- duplicate name validation
- add a validation in agent-sdk

https://app.abstract.com/projects/9ec92568-60a2-4fee-8215-5aa997d52428/branches/dc10bcee-d9a1-44f9-b644-8f843c6f1a19/commits/762f23dd8207318f36641e723d6d7dcf1d9c6451/files/95d5757f-f10e-43f6-ad50-0faa236217fd/layers/EF3FA754-C31F-4198-A5C4-2B0CCDD91E3F?collectionId=cc5337ea-21d1-4d7d-8d0f-97b0e5414ebb&collectionLayerId=14bb50f7-1ff0-4149-aa50-cc010f4ad369

**Comment by sudeshrshetty** [comment]
@talwinder50 in agent-sdk in [this](https://github.com/trustbloc/agent-sdk/blob/main/cmd/wallet-js-sdk/src/collection/collections.js#L60) line, change `uuid()` to `hashOf(name)`.

You may have to add hash function in util.
