### ISSUE TITLE
Link Vault Card to Credential screen

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/wallet#1227]
https://github.com/trustbloc/wallet/blob/main/cmd/wallet-web/src/components/Vaults/VaultCard.vue#L33-L62
https://github.com/trustbloc/wallet/blob/main/cmd/wallet-web/src/components/Vaults/VaultCard.vue#L3-L32

Make Add Vault Clickable

![image (2)](https://user-images.githubusercontent.com/7862595/141357417-92f4cf45-13a8-45b9-9370-f6eaddf1402c.png)

**Comment by birtony** [comment]
This has been implemented. WCAG accessibility requirements for `VaultCard` are tracked in #1357
