### ISSUE TITLE
Auto refresh when vault is added 

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/wallet#1259]
Use vue reactivity to see the newly created vault right on the screen without page refresh .

**Comment by birtony** [comment]
I have looked closer into how we currently process/create vaults and it seems that we need to decide on the following questions first before we can implement corresponding solution to this issue:

> _Can we safely store fetched vaults in `Vuex` store? If so, how exactly?_

Depending on the answer, we will then be able to implement one of the following approaches:

### 1. Store vaults locally in `Vuex`
- pros: minimizing the number of API calls, optimizing UI reactivity (we can have the list of vaults updated in the UI after adding a new vault almost instantly, while the vault is saved to `CollectionManager` in the background)
- cons: potential security risks
### 2. Do not store vaults locally and make an API call to the `CollectionManager` every time we need to access vaults
- pros: no data is stored locally -> potentially lower security risks
- cons: greater number of API calls required, less effective UI reactivity (to update the list vaults after adding a new one, we'd need to make an API call and wait for results before we can update the UI)

We also have a similar dilemma with credentials.

@sudeshrshetty @rolsonquadras @talwinder50
