### ISSUE TITLE
Vault name mismatch in credential screen

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/wallet#1277]
vault label shows "default vault" instead of "all vaults

https://user-images.githubusercontent.com/10111768/144448190-37e6c01a-5e93-4fcc-981a-9eba06a45d25.mov

**Comment by talwinder50** [comment]
https://github.com/trustbloc/wallet/blob/c3d1be52f209d64519a3afb9e884a5904dfc2044/cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue#L5
