### ISSUE TITLE
Check if we can set`id`s to `default` and `vault` flyout menus, since we add it as a prop

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/wallet#1288]
Should we also set `id`s to `default` and `vault` flyout menus, since we add it as a prop?

_Originally posted by @birtony in https://github.com/trustbloc/wallet/pull/1285#discussion_r763380043_

**Comment by birtony** [comment]
Making `id` prop `required` caused errors from other places where `FlyoutMenu` is used:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/33902374/144929492-fff323a2-dcae-48a1-af60-f57a3defb97d.png">
