### ISSUE TITLE
vault name - typed character count mismatch

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/wallet#1373]
0:17 of the screen recording - no name is typed, but system shows 7/42 count

https://user-images.githubusercontent.com/10111768/146986308-0f09b73b-2494-4f40-9ecb-eb91601be578.mov

**Comment by birtony** [comment]
cc @talwinder50

**Comment by talwinder50** [comment]
This is fixed with recent changes @rolsonquadras  can you please confirm ??

**Comment by rolsonquadras** [comment]
verified - thanks @talwinder50
