### ISSUE TITLE
Support for Credential Manifest data model

### ISSUE THREAD

**Issue by sudeshrshetty** [trustbloc/wallet#1392]
- [ ] proposing in universal wallet
- [ ] implementation in aries
- [ ] implementation in agent SDK
- [ ] wallet JS SDK tests
- [ ] taking priority over credential display data (design + implementation for fallback strategy)
- [ ] wallet UI changes to use credential manifest

**Comment by rolsonquadras** [comment]
This is a duplicate of https://github.com/trustbloc/wallet/issues/1398
