### ISSUE TITLE
Automation test for CHAPI Store is failing

### ISSUE THREAD

**Issue by birtony** [trustbloc/wallet#1439]
[CHAPI Store flow fails in our automation tests](https://github.com/trustbloc/wallet/runs/4867127862?check_suite_focus=true) (used to [pass](https://github.com/trustbloc/wallet/actions/runs/1714902153/attempts/1) on the same code yesterday). Reproducible on staging environment. See the videos below:

https://user-images.githubusercontent.com/33902374/150128084-ef2684f4-8e81-4be3-a541-68e056d5e8ae.mov

https://user-images.githubusercontent.com/33902374/150128150-c5bc4c68-1752-4a39-80e1-f07ebf825a2d.mov

https://user-images.githubusercontent.com/33902374/150128192-d387fde9-b60d-4678-8df6-cf35b2f97c1b.mov

**Comment by birtony** [comment]
@rolsonquadras @sudeshrshetty

**Comment by birtony** [comment]
I can see intermittent issue with the CHAPI modal. Sometimes the first screen with the `Next` button does not show up, but it rather display the vault selection right away and also selects the vault for you. On the screenshot you can see the very next thing that showed up after I clicked `Store` button:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/33902374/150142964-a572a016-a9f0-489d-9f85-83c74f27aa5b.png">

**Comment by rolsonquadras** [comment]
Latest release of CHAPI (Jan 18) might be causing the issue - https://github.com/digitalbazaar/credential-handler-polyfill/commits/main. We need to revisit CHAPI steps and align with the new release

**Comment by rolsonquadras** [comment]
The "Remember my choice for this site" box is checked by default now. Next time when we control goes to CHAPI iframe, user is taken directly to the wallet. Also, the wallet images are not loading now.

![chapi-remember-true-by-default](https://user-images.githubusercontent.com/10111768/150167400-72227b0a-307b-4af2-ac19-43665c49de22.png)

**Comment by birtony** [comment]
Yeah, we might need `cors` policy to allow for images to load, let's discuss after the blocking part of the issue is resolved @rolsonquadras
