### ISSUE TITLE
[DWC] Update rename credential modal

### ISSUE THREAD

**Issue by birtony** [trustbloc/wallet#1516]
Simply updating name and/or description of credential metadata will update name/description of credential metadata without actually impacting original credential data.
Reference: [Updating Credential Metadata](https://github.com/trustbloc/agent-sdk/blob/5c6ff22c50603618b30279f94bf566cdd051e4e6/cmd/wallet-js-sdk/test/specs/credential/credential-manager.spec.js#L177-L191)

**Comment by rolsonquadras** [comment]
This is a duplicate of https://github.com/trustbloc/wallet/issues/1344

**Comment by rolsonquadras** [comment]
UI for renaming credential need to be implemented according to the designs.

**Comment by rolsonquadras** [comment]
This has been implemented
