### ISSUE TITLE
[waci-issuance-test] Support to dynamically define credential

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/wallet#1609]
Currently, Credential data is hardcoded in demo-issuer - https://github.com/trustbloc/wallet/blob/7c8ffe9c0c1c587b43748ade053ecc832821f40f/test/mock/adapter/sampledata/sample_prc_fulfillment.json. We can't change VC data or issue new VC data dynamically. 

We need to update demo-issuer to support dynamically passing the credentials.

**Comment by sudeshrshetty** [comment]
Fixed in https://github.com/trustbloc/wallet/pull/1656
