### ISSUE TITLE
Rename Vue components to always be multi-word

### ISSUE THREAD

**Issue by birtony** [trustbloc/wallet#1662]
Our Vue components/pages naming conventions may be improved to [prevent conflicts with existing and future HTML elements](https://vuejs.org/style-guide/rules-essential.html#use-multi-word-component-names). I'm thinking we could look into renaming our components in the following folders:
- [ ] `cmd/wallet-web/src/components` - here we could add the `The` prefix to all components (`Signout` -> `TheSignout`)
- [ ] `cmd/wallet-web/src/pages` - here we could add the `Page` postfix to all components (`Vaults` -> `VaultsPage`)
- [ ] `cmd/wallet-web/src/layouts` - here we could add the `Layout` postfix to all components (`Get` -> `GetLayout`)
- [ ] `cmd/wallet-web/src/router` - here we could add the `The` prefix (`Root` -> `TheRoot`)

Suggestions on best naming conventions are welcome :slightly_smiling_face:

**Comment by rolsonquadras** [comment]
@birtony @talwinder50 

> * [ ]  `cmd/wallet-web/src/components` - here we could add the `The` prefix to all components (`Signout` -> `TheSignout`)
> *

Is `The` prefix mandatory ? Or can we use any other prefix ?

**Comment by birtony** [comment]
We can use any prefix @rolsonquadras
