### ISSUE TITLE
Initiate GNAP flow - Wallet integration

### ISSUE THREAD

**Issue by birtony** [trustbloc/wallet#1678]
We need to maintain support for the existing authentication flow while also introducing the new GNAP flow. Thus, we should:
- [ ] Add a separate route (`/gnap`) to [the Vue router](https://github.com/trustbloc/wallet/blob/main/cmd/wallet-web/src/router/routes.js) which would participate in the new authentication flow
- [ ] Add [navigation handlers in Vue route](https://github.com/trustbloc/wallet/blob/main/cmd/wallet-web/src/router/index.js#L16)r to handle necessary redirects for the new authentication flow
- [ ] Implement key pair generation logic to encrypt GNAP requests according to [the specs](https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-09.html)

**Comment by birtony** [comment]
https://github.com/trustbloc/auth/issues/225 is also related to this issue

**Comment by talwinder50** [comment]
Use JS crypto to create key pair and make sure its accessible all through the session till user log out or user session expire and we need to store the reference of the key pair into vue store 


In the /gnap --->create key pair ---? redirect to oath server --->  part of resp to redirect --> wallet needs to have page.

**Comment by Moopli** [comment]
related: #1699
