### ISSUE TITLE
BDD Mock auth server for GNAP flow

### ISSUE THREAD

**Issue by Moopli** [trustbloc/wallet#1700]
Should give mock responses for a successful GNAP flow, _without_ validating HTTP signatures.
- Auth Request Handler: handle POST with AuthRequest: save client nonce, and client redirect uri, create and save server nonce, respond with server nonce, hardcoded login redirect URI, hardcoded continuation URI, and hardcoded continue token.
- Redirect Handler: gets redirect from client, calculates interaction hash, redirects back to client's redirect URI, with `hash` and hardcoded(?) `interact_ref` query param.
- Continue Handler: handle POST with ContinueRequest: return hardcoded access token

**Comment by rolsonquadras** [comment]
This is not applicable now
