### ISSUE TITLE
Show loading state while finishing user authentication

### ISSUE THREAD

**Issue by birtony** [trustbloc/wallet#1809]
![image](https://user-images.githubusercontent.com/33902374/180791187-d8212c23-e292-4f44-8603-40950df9e2b3.png)

**Comment by HeidiHan0000** [comment]
For now, a spinner was added as the loading indicator in https://github.com/trustbloc/wallet/pull/1812, but from talking to the design team, the loading state should be the skeleton loaders for the corresponding page, not the general spinner.
