### ISSUE TITLE
Credential display uses fields from metadata instead of resolved manifest

### ISSUE THREAD

**Issue by HeidiHan0000** [trustbloc/wallet#1824]
When a VC that is missing the name property is saved into wallet, the wallet shows a credential with an empty title.
<img width="1670" alt="Screen Shot 2022-07-26 at 3 11 51 PM" src="https://user-images.githubusercontent.com/44453261/181504663-450998e9-72ef-4403-8e36-29a825e47dd6.png">

In the pages related to saving (ex `WACIIssuePage`), the title is shown. This is because `WACIIssuePage` uses the credential name from the credential manifest (returned from `resolveManifest`) while the `CredentialsPage` uses the credential name from `getCredentialMetadata`

**Comment by sudeshrshetty** [comment]
We should always use credential type to lookup and find right manifest.
https://github.com/trustbloc/wallet/blob/main/cmd/wallet-web/src/config/credential-output-descriptors.json#L2

Credential Name can be anything & it is optional too.
