### ISSUE TITLE
Credential fulfillment renamed to credential response

### ISSUE THREAD

**Issue by birtony** [trustbloc/wallet#1868]
https://identity.foundation/credential-manifest/#credential-response

**Comment by sudeshrshetty** [comment]
https://github.com/decentralized-identity/credential-manifest/commit/a9f10cdc4ad0b6c8e2ea7a0e17b41d89daeb1212/

3 solutions for now,

1. having previous credential fulfillment context inside aries contexts, 
2. pointing to new context hosted by TrustBloc (credential fulfillment context)
3. migrating from credential fulfillment to credential response

I would suggest going with option 1 or 2 for now

**Comment by rolsonquadras** [comment]
Old context url https://identity.foundation/credential-manifest/fulfillment/v1
