### ISSUE TITLE
WebWallet DIDComm flow: Rely on offer credential protocol message instead of manifest VC

### ISSUE THREAD

**Issue by sudeshrshetty** [trustbloc/wallet#214]
**Current Behaviour:**

- issuer performs didexchange with wallet and sends manifest VC (containing supported VC schemas) to wallet along with didexchange invitation.
- wallet stores manifest VC like any other regular VC
- wallet runs presentation definition query against manifest VC(only schema checks) when any regular stored credential failed to match request criteria.
- if matching manifest VC found, then wallet performs '[issue credential - request credential](https://github.com/hyperledger/aries-rfcs/blob/master/features/0036-issue-credential/README.md#request-credential)' to respective issuer to get consent VC
- wallet returns consent VC to verifier for requested query criteria

**Drawbacks**: 

- once didexchange is done, issuer can't update manifest VC dynamically 
    - when a new credential type is going to be offered by that issuer
    - when issuer updates schema or supports new schema.
    - when issuer stops supporting any existing schema or credential
- in web wallet, presentation def query match against manifest VC only checks schema given in manifest VC credential subject, it cannot check [constraints](https://identity.foundation/presentation-exchange/#input-descriptors) (like vc.credentialSubject.age>18, vc.credentialSubject.degree == bachelorsDegree) since those data cannot be shared in advance by issuer
- risk of verifier changing constraints while asking for actual credential from issuer

**Proposal**
Replace manifest VC with aries [offer credential](https://github.com/hyperledger/aries-rfcs/blob/master/features/0036-issue-credential/README.md) from [issuer credential protocol](https://github.com/hyperledger/aries-rfcs/blob/master/features/0036-issue-credential/README.md#offer-credential) where,

- Issuer doesn't need to send manifest VC during didexchange with webwallet, it can send offer-credential message anytime as a didcomm message to add, update, delete supported schemas.
- offer credential also has a feature to send credential preview which can be used for matching presentation definition query including [constraints](https://identity.foundation/presentation-exchange/#input-descriptors) (like vc.credentialSubject.age>18, vc.credentialSubject.degree == bachelorsDegree) .
- verifier cannot change presentation exchange constraints while getting actual credential from issuer

**Comment by llorllale** [comment]
@sudeshrshetty note: we're targetting [issue-credential v2](https://github.com/hyperledger/aries-rfcs/blob/master/features/0453-issue-credential-v2/README.md)

**Comment by sudeshrshetty** [comment]
Offer credential attachment type : https://hackmd.io/fV7Qwn01RZyBlCGCTC8mwQ?view

**Comment by llorllale** [comment]
@sudeshrshetty see https://github.com/llorllale/aries-rfcs/blob/issue-cred-v2-presdef/features/0453-issue-credential-v2/registry/dif-credential-manifest-v1.0.md
