### ISSUE TITLE
Verify if we are affected by GHSA-p6mc-m468-83gw 

### ISSUE THREAD

**Issue by MarwaAbdallah** [trustbloc/wallet#239]
Hi team, we received this advisory by email.
Can you please look into it, verify if issue is present, and provide a fix ? Thanks.

![image](https://user-images.githubusercontent.com/7713988/87948923-538caf00-ca73-11ea-943e-432e4608ecc5.png)

**Comment by llorllale** [comment]
@MarwaAbdallah this is being handled in PRs #237 and #238

**Comment by rolsonquadras** [comment]
> #238

@MarwaAbdallah these PRs have been merged. Please verify.
