### ISSUE TITLE
Use SDS for manifest store and connections store

### ISSUE THREAD

**Issue by DRK3** [trustbloc/wallet#268]
See the relevant comment in walletManager.js

**Comment by llorllale** [comment]
Comment in `walletManager.js`: https://github.com/trustbloc/edge-agent/blob/84c302eb866bdadfb7039477efb0fc6b9a02b039/cmd/user-agent/src/pages/chapi/wallet/register/walletManager.js#L25

This component is making use of `KeyValueStore` that uses indexedDB as backend: https://github.com/trustbloc/edge-agent/blob/45c5b33ee0de8b20dcfe8e7ab310d8cb506e3342/cmd/user-agent/src/pages/chapi/wallet/common/keyValStore.js#L22-L46

**Comment by rolsonquadras** [comment]
This has been implemented
