### ISSUE TITLE
Derive the SDS URL and vault ID from the hub-auth bootstrap data

### ISSUE THREAD

**Issue by DRK3** [trustbloc/wallet#271]
Currently edge-agent has the SDS URL directly passed in. Instead, edge-agent should take in the bootstrap data/hub-auth URL and use that to derive the SDS URL.

Also, the vault ID should come from the bootstrap data. Right now a new vault (and vault ID) is created whenever edge-agent starts.

**Comment by rolsonquadras** [comment]
This has been implemented
