### ISSUE TITLE
mobile: support wallets via edge-agent

### ISSUE THREAD

**Issue by ToJen** [trustbloc/wallet#329]
**What I'm trying to do**

Create bindings such that the `edge-agent` library can be used from within a mobile application.

**Expected result**

A folder under [cmd](https://github.com/trustbloc/edge-agent/tree/master/cmd) that will have importable libraries for native Android and iOS apps.

**Checklist**

_Confirm this..._
- [ ] register wallet
- [ ] create, import and get DIDs
- [ ] generate presentation
- [ ] relationships
- [ ] dev mode:
   - [ ] connections
      - [ ] (un)register with a mediator
      - [ ] create and receive invitations
      - [ ] view connections
   - [ ] issue credentials
   - [ ] present proof

**Comment by rolsonquadras** [comment]
These are implemented in https://github.com/trustbloc/agent-sdk/tree/main/cmd/agent-mobile
