### ISSUE TITLE
User primary key creation - Onboarding vs Login

### ISSUE THREAD

**Issue by Baha-sk** [trustbloc/wallet#350]
Build the Onboarding and Login flow for a user to access keys.

The main flow in the user agent to create a primary key during onboarding is as follows:

1. Vue.js obtains a secret
2. Vue.js derives a primary key from secret (via hkdf.NewMasterLock()). Note: Primary key is never stored and is not sharable in DID documents.
3. Vue.js splits the secret into shares.
4. Vue.js creates a new key store sending one share along with the Create KeyStore rest call to the Key Server.
5. Vue.js prepares the storage of the second share in SDS for Hub-Auth:
- Vue.js instantiates framework with secretLock service using the primary key (and should remove primary key from memory)
- Vue.js creates “SDS Vault” keys via the framework
- Vue.js creates an SDS Vault via the framework and sets one of the “SDS Vault” keys as the controller
- Vue.js creates via the framework an SDS encrypted document wrapping one secret share and setting the recipient to be... the “SDS Vault” key - this encrypted document is the hub-auth share

6. Vue.js stores the SDS doc ref in hub-auth of the document created in step 5 above.

The issue with this flow is during login, the user agent cannot fetch the primary key half stored in SDS before accessing the keys in the KMS. In order to access the KMS, the user needs to build the primary which depends on the key half in SDS.

We need to provide a way to circumvent this circular root problem.

**Comment by llorllale** [comment]
@Baha-sk 

* the secret shares are to be stored in SDS vaults by the user agent directly
* if the primary key is never persisted anywhere, and the "SDS Vault" keys are encrypted with it, and these "SDS Vault" keys control the SDS vaults, and in these same vaults we're storing the secret's shares, then we have the chicken+egg problem.... how can we unlock the "SDS Vault" keys without having the "secret" on hand.... ?

**Comment by llorllale** [comment]
@Baha-sk 

> The issue with this flow is during login, the user agent cannot fetch the primary key half stored in SDS before accessing the keys in the KMS. In order to access the KMS, the user needs to build the primary which depends on the key half in SDS.
> 
> We need to provide a way to circumvent this circular root problem.

1. edge-agent has an access_token from hub-auth
1. edge-agent has a primary key
1. edge-agent splits primary key into shares
1. edge-agent asks the key server for an auth key KID (authZ with access_token)
1. edge-agent creates 1 SDS vault per key share and set the vault's controller to the primary key (did:key) (authZ with access_token)
1. edge-agent creates 1 document per key share at the SDS vaults and includes the key server's key KID as a recipient (authZ with primary key)
1. edge-agent updates bootstrap info with key locations at hub-auth (authZ with access_token)
1. edge-agent purges the primary key from memory
1. edge-agent inits remote KMS with the key share locations
1. key server fetches key shares from SDS vaults

**Comment by Baha-sk** [comment]
New requirements from Troy:
```
Points I captured from @troyronda :
separation of user data from key server
Key Server NEVER has access to user data - not even encrypted
user device performes encryption ops for user-sensitive data
in all respects: separate user data storage, and key server storage + ops
purvue of Key Server is to handle authentication and key exchange ops
  * implies: Key Server must not ever have user data touching it in ANY form
  * implies: Key server cannot have any access to keys that were used to encrypt user data
only user device EVER touches user data in encrypted or decrypted form
only the user's SDS vault can touch the user data in decrypted mode
user must have control of their SDS vault
bootstrapping component (http-server) only system that can ever see keys related to user data, NOT the user data itself
when user is not currently logged in, none of their keys exist in full-form in any system
when user logs in the keys are reconstructed for a certain amount of time
hub-auth cannot have the full key
  * the only system that can have the key is the user's device and a service that may assist the user's device when bootstrapping
keys split between services that do auth, and user-controlled storage

```

**Comment by rolsonquadras** [comment]
This has been implemented
