### ISSUE TITLE
broken demo

### ISSUE THREAD

**Issue by llorllale** [trustbloc/wallet#560]
(tested against 6ff83c1722d337686252f04b70ccc81c89c2f44b)

The [demo](https://github.com/trustbloc/edge-agent/blob/master/docs/test/test.md) seems broken. I have not been able to [establish a did-connection between agents](https://github.com/trustbloc/edge-agent/blob/master/docs/test/test.md#how-to-establish-a-did-connection-between-agents).

I am not sure if the mediators are registering properly. For example: I log in and go to Connections. I see a mediator registered. I can click on another sidebar section (eg. Issue Credential), but when I click back to Connections the mediator is gone from the Mediator section. Attempts to manually register the mediator do not result in obvious errors.

From edge.router.agent.example.com:

```
[hub-router/operations] 2020/12/01 19:54:09 UTC - httputil.WriteResponseWithLog -> INFO endpoint=[/didcomm/invitation] msg=[success]
```

From the browser's console:

```
 [aries-framework/out-of-band/service] 2020/12/01 19:54:09 UTC - n/a -> ERROR command=[out-of-band] action=[handleDIDEvent] [] errMsg=[ignored]
```

Another problem (perhaps related?) is that - after I _think_ that both agents have mediators registered, I create an invitation on one and receive on the other. The second agent's connection state remains `null`. The first agent never receives the response.

**Comment by rolsonquadras** [comment]
This is not applicable now.
