### ISSUE TITLE
web-wallet: wrong KMS URLs being stored in bootstrap data and then used

### ISSUE THREAD

**Issue by llorllale** [trustbloc/wallet#574]
Wallet-web is bypassing oathkeeper for normal key operations (create, sign, etc.).

1. the keystoreURL is [retrieved from the response header](https://github.com/trustbloc/edge-agent/blob/dd46fb2c8c542b77735865d1a87abd17dcc73113/pkg/restapi/oidc/operations.go#L709-L710), which will have the ops keyserver's URL
2. this keystore URL is then [saved to bootstrap data](https://github.com/trustbloc/edge-agent/blob/dd46fb2c8c542b77735865d1a87abd17dcc73113/pkg/restapi/oidc/operations.go#L620-L633)
3. it is then afterwards [pulled during bootstrap](https://github.com/trustbloc/edge-agent/blob/f157210518f2ff120682ea85b96c143de430b484/cmd/wallet-web/src/store/modules/options.js#L88-L90) and used to communicate with the ops key server

[hub-auth serves the correct URLs](https://github.com/trustbloc/hub-auth/blob/48d4c6f991b8572826803caa92175e109cd4a71e/pkg/restapi/operation/models.go#L10).

(recall the earlier thread in PR #508)

**Comment by rolsonquadras** [comment]
This is not applicable now.
