### ISSUE TITLE
CHAPI Bridge: Managing application URLs in wallet-server

### ISSUE THREAD

**Issue by sudeshrshetty** [trustbloc/wallet#645]
For Design, refer : https://github.com/trustbloc/edge-agent/issues/633

As per current design wallet-server will be coupled to one app URL which can be a homepage for single app or multiple apps.

For example: wallet server returns below response during `create-invitation`

```
{"url":"https://demo.walletmobile.app/load?oob=eyJAaWQiOiI0ZGMwYTBlNS0wZWNmLTQxNmQtOWZhOS1kZDg1MmFiMzQ5ZDIiLCJAdHlwZSI6Imh0dHBzOi8vZGlkY29tbS5vcmcvb29iLWludml0YXRpb24vMS4wL2ludml0YXRpb24iLCJsYWJlbCI6InVzZXItYWdlbnQiLCJzZXJ2aWNlIjpbeyJJRCI6ImQ3ZTEwYTFjLWJjZGMtNDJhMi05NjcwLTU3M2Y3Njg1YTEyNyIsIlR5cGUiOiJkaWQtY29tbXVuaWNhdGlvbiIsIlByaW9yaXR5IjowLCJSZWNpcGllbnRLZXlzIjpbIkhwb2I5RGRkV3Nqc3BZRUZVTmE2UHNqdGtuUTlLUFJOYnZodExvUWNRc3VRIl0sIlJvdXRpbmdLZXlzIjpudWxsLCJTZXJ2aWNlRW5kcG9pbnQiOiJodHRwczovL3VzZXItYWdlbnQuZXhhbXBsZS5jb206ODA5MiIsIlByb3BlcnRpZXMiOm51bGx9XSwicHJvdG9jb2xzIjpbImh0dHBzOi8vZGlkY29tbS5vcmcvZGlkZXhjaGFuZ2UvMS4wIl19"}
```

Currently `https://demo.walletmobile.app/load` is configured in wallet-server using startup argument (ENV argument).

There are many ways this app URL can be managed.

1. Single application URL for one mobile app for all create-invitation calls, can be configured once through startup argument (current implementation)
2. Single application URL as an index page for multiple wallet mobile apps( no change to current implementation in wallet-server)
3. Dedicated endpoint in wallet-server for add/remove/update of application URLs (and public DIDs for oob invitation). And in this approach a verifier/issuer can explicitly choose application URL while creating invitation

**Comment by rolsonquadras** [comment]
This is not applicable now.
