### ISSUE TITLE
wallet-server: return 401 Unauthorized on session expiration, allow relogin

### ISSUE THREAD

**Issue by llorllale** [trustbloc/wallet#691]
The server is returning error code `BadRequest` instead of `Unauthorized` when the session expires and wallet-web attempts to load the user's profile again:

https://github.com/trustbloc/edge-agent/blob/16f675df5cfb24bc157cbaaa5d653bb0eb29747e/pkg/restapi/oidc/operations.go#L386-L392

We need to differentiate the error conditions further and detect when the user's session has expired such that a 401 can be returned. Note that we'll be rolling a custom and simple http authentication scheme: https://stackoverflow.com/a/10135309/1623885

**Comment by rolsonquadras** [comment]
This has been implemented
