### ISSUE TITLE
BDD Test Sign up fix 

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/wallet#838]
Bdd test complaining about hydra cookie missing. Needs more investigation. Low priority for now. 

url: https://localhost:8045/oauth2/callback?code=fIv9Jx2mI6Eq6dU2li8vZIjihaMwhSACsUUyshL_n1E.5EGxlncHuNAVktO20bx4r8do-OQX892jZhxoGXucWTg&scope=openid%20profile%20email&state=899fe848-2aba-405e-afe8-edf28b01fa3c
body: missing hydra login challenge cookie

**Comment by rolsonquadras** [comment]
This is not applicable now as we have moved to ui-automation tests.
